--
-- File generated with SQLiteStudio v3.4.16 on qui. mar. 27 17:50:44 2025
--
-- Text encoding used: UTF-8
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: tb_bairro
CREATE TABLE IF NOT EXISTS tb_bairro (
    N_ID     INTEGER   PRIMARY KEY AUTOINCREMENT,
    N_ZONA   INTEGER   REFERENCES tb_zona (N_ID),
    T_BAIRRO TEXT (40) 
);
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (1, 6, 'Alvorada');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (2, 6, 'Bairro da Paz');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (3, 6, 'Dom Pedro');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (4, 6, 'Planalto');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (5, 6, 'Redenção');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (6, 6, 'Ajuricaba');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (7, 6, 'Campos Elíseos');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (8, 6, 'Déborah');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (9, 6, 'Hileia');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (10, 6, 'Jardim Versailles');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (11, 6, 'Kíssia');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (12, 6, 'Parque Riachuelo');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (13, 6, 'Promorar');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (14, 6, 'São Pedro');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (15, 5, 'Adrianópolis');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (16, 5, 'Aleixo');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (17, 5, 'Chapada');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (18, 5, 'Flores');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (19, 5, 'Nossa Senhora das Graças');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (20, 5, 'Parque 10 de Novembro');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (21, 5, 'São Geraldo');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (22, 5, 'Bairro da União');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (23, 5, 'Eldorado');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (24, 5, 'Jardim Amazonas');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (25, 5, 'Jardim Primavera');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (26, 5, 'Jardim Sakura');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (27, 5, 'Parque das Laranjeiras');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (28, 5, 'Parque Shangri-lá');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (29, 5, 'Portal do Japão');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (30, 5, 'Vieiralves');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (31, 5, 'Vila Amazonas');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (32, 3, 'Armando Mendes');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (33, 3, 'Colônia Antônio Aleixo');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (34, 3, 'Coroado');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (35, 3, 'Distrito Industrial II');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (36, 3, 'Gilberto Mestrinho');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (37, 3, 'Jorge Teixeira');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (38, 3, 'Mauazinho');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (39, 3, 'Puraquequara');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (40, 3, 'São José Operário');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (41, 3, 'Tancredo Neves');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (42, 3, 'Zumbi dos Palmares');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (43, 3, 'Acariquara');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (44, 3, 'Braga Mendes');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (45, 3, 'Castanheira');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (46, 3, 'Cidade do Leste');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (47, 3, 'Colina do Aleixo');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (48, 3, 'Grande Vitória');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (49, 3, 'João Bosco');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (50, 3, 'João Paulo');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (51, 3, 'Monte Sião');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (52, 3, 'Nova Conquista');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (53, 3, 'Nova Floresta');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (54, 3, 'Nova Vitória');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (55, 3, 'Novo Reino');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (56, 3, 'Ouro Verde');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (57, 3, 'Petro');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (58, 3, 'Santa Inês');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (59, 3, 'São Lucas');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (60, 3, 'Valparaíso');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (61, 1, 'Cidade de Deus');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (62, 1, 'Cidade Nova');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (63, 1, 'Colônia Santo Antônio');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (64, 1, 'Colônia Terra Nova');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (65, 1, 'Lago Azul');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (66, 1, 'Monte das Oliveiras');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (67, 1, 'Nova Cidade');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (68, 1, 'Novo Aleixo');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (69, 1, 'Novo Israel');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (70, 1, 'Santa Etelvina');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (71, 1, 'Águas Claras');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (72, 1, 'Alfredo Nascimento');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (73, 1, 'Aliança com Deus');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (74, 1, 'Amadeu Botelho');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (75, 1, 'Amazonino Mendes');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (76, 1, 'Américo Medeiros');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (77, 1, 'Boas Novas');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (78, 1, 'Carlos Braga');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (79, 1, 'Colônia Cachoeira Grande');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (80, 1, 'Colônia Japonesa');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (81, 1, 'Fazendinha');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (82, 1, 'Francisca Mendes');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (83, 1, 'Galileia');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (84, 1, 'Gustavo Nascimento');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (85, 1, 'Ismail Aziz');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (86, 1, 'Jardim Canaranas');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (87, 1, 'Jardim Independente');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (88, 1, 'Jardim Paulista');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (89, 1, 'Jesus me Deu');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (90, 1, 'José Bonifácio');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (91, 1, 'Manôa');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (92, 1, 'Monte Pascoal');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (93, 1, 'Monte Sinai');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (94, 1, 'Mundo Novo');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (95, 1, 'Nossa Senhora de Fátima');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (96, 1, 'Nossa Senhora do Perpétuo Socorro');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (97, 1, 'Núcleo 3');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (98, 1, 'Núcleo 4');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (99, 1, 'Núcleo 5');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (100, 1, 'Núcleo 7');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (101, 1, 'Núcleo 8');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (102, 1, 'Núcleo 9');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (103, 1, 'Núcleo 11');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (104, 1, 'Núcleo 12');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (105, 1, 'Núcleo 13');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (106, 1, 'Núcleo 15');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (107, 1, 'Núcleo 16');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (108, 1, 'Núcleo 21');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (109, 1, 'Núcleo 22');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (110, 1, 'Núcleo 23');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (111, 1, 'Núcleo 24');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (112, 1, 'Omar Aziz');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (113, 1, 'Parque das Garças');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (114, 1, 'Parque das Nações');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (115, 1, 'Parque dos Buritis');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (116, 1, 'Parque dos Ingleses');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (117, 1, 'Riacho Doce');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (118, 1, 'Vale do Sinai');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (119, 1, 'Vitória Régia');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (120, 4, 'Compensa');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (121, 4, 'Glória');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (122, 4, 'Lírio do Vale');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (123, 4, 'Nova Esperança');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (124, 4, 'Ponta Negra');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (125, 4, 'Santo Agostinho');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (126, 4, 'Santo Antônio');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (127, 4, 'São Jorge');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (128, 4, 'São Raimundo');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (129, 4, 'Tarumã');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (130, 4, 'Tarumã-Açu');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (131, 4, 'Vila da Prata');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (132, 2, 'Betânia');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (133, 2, 'Cachoeirinha');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (134, 2, 'Centro');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (135, 2, 'Colônia Oliveira Machado');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (136, 2, 'Crespo');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (137, 2, 'Distrito Industrial I');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (138, 2, 'Educandos');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (139, 2, 'Japiim');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (140, 2, 'Morro da Liberdade');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (141, 2, 'Nossa Senhora de Aparecida');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (142, 2, 'Petrópolis');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (143, 2, 'Praça 14 de Janeiro');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (144, 2, 'Presidente Vargas');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (145, 2, 'Raiz');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (146, 2, 'Santa Luzia');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (147, 2, 'São Francisco');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (148, 2, 'São Lázaro');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (149, 2, 'Vila Buriti');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (150, 2, 'Ceasa');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (151, 2, 'Getúlio Vargas');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (152, 2, 'Lagoa Verde');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (153, 2, 'Morada do Sol');
INSERT INTO tb_bairro (N_ID, N_ZONA, T_BAIRRO) VALUES (154, 2, 'Nova República');

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
